name: Docker Image CI 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.AZURE_CONTAINER_USER }}
        password: ${{ secrets.AZURE_CONTAINER_PWD }}
        login-server: imaginagrupo1.azurecr.io 
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag imaginagrupo1.azurecr.io/imagina-project-v1:${{ github.sha }}
        docker push imaginagrupo1.azurecr.io/imagina-project-v1:${{ github.sha }}
